# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-08 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.IntegerField(default=0),
        ),
    ]
