# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-09 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_users_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=5)),
                ('month', models.CharField(max_length=2)),
                ('day', models.CharField(max_length=2)),
            ],
        ),
    ]
