# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-09 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitions',
            name='id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterField(
            model_name='competitions',
            name='codingLink',
            field=models.CharField(max_length=800, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='nameOfUser',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
