# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-09 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20171010_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='id',
        ),
        migrations.AlterField(
            model_name='ratings',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.Users'),
        ),
    ]
