# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-09 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20171010_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='date',
            field=models.CharField(default='1998-01-06', max_length=300),
        ),
    ]
