# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-08 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codingLink', models.CharField(max_length=800)),
                ('compName', models.CharField(max_length=300)),
                ('websiteName', models.CharField(max_length=300)),
                ('startDate', models.CharField(max_length=300)),
                ('endDate', models.CharField(max_length=300)),
                ('startTime', models.CharField(max_length=300)),
                ('endTime', models.CharField(max_length=300)),
                ('duration', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spoj', models.IntegerField(default=0)),
                ('leet', models.IntegerField(default=0)),
                ('hackerRank', models.IntegerField(default=0)),
                ('codeChef', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfUser', models.CharField(max_length=300)),
                ('emailId', models.CharField(max_length=300)),
                ('firstName', models.CharField(max_length=300)),
                ('lastNmae', models.CharField(max_length=300)),
                ('profilePic', models.CharField(max_length=500)),
                ('birthdate', models.CharField(max_length=12)),
                ('language', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='ratings',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Users'),
        ),
    ]
